[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps --include=dev"]

[phases.build]
cmds = ["MEDUSA_ADMIN_DISABLE=false NODE_OPTIONS='--max-old-space-size=4096' npm run build && mkdir -p public && cp -r dist/public/admin public/"]

[start]
cmd = "NODE_OPTIONS='--max-old-space-size=1536' npm run start"
